name: CI
on: [pull_request, push]

jobs:
  ci:
    name: Build
    runs-on: windows-latest

    strategy:
      fail-fast: false
      matrix:
        include:
          - arch: i686
            msystem: MINGW32
          - arch: x86_64
            msystem: MINGW64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup msys2
        uses: msys2/setup-msys2@v2
        with:
          msystem: ${{ matrix.msystem }}
          install: mingw-w64-${{ matrix.arch }}-toolchain
          update: true

      - name: Build qBittorrent
        shell: msys2 {0}
        run: |
          MINGW_ARCH=${{ matrix.msystem }} makepkg-mingw --skippgpcheck --syncdeps --noconfirm

      - name: Upload build artifacts
        uses: actions/upload-artifact@v2
        with:
          name: qBittorrent_${{ matrix.arch }}
          path: |
            mingw-w64-*.pkg.tar.*
